
name: API Test Framework test123 again

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: '1.8'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests
      run: mvn clean test -Dsuite=suite -x
